name: Free Disk Space (Ubuntu)
on:
  workflow_dispatch:
    inputs:
      min-file-size:
        description: "Minimum file size to remove (in KB)"
        required: false
  push:
    branches:
      - main
  pull_request:

jobs:
  free-disk-space:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # If there is a problem with this GitHub Actions, this step will fail
      - name: Free Disk Space
        uses: ./
        with:
          tool-cache: true

          # all of these default to true, but feel free to set to
          # false if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
          min-file-size: ${{ inputs.min-file-size }}
